# Generated by Django 2.0.5 on 2018-05-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30, verbose_name='Nom')),
                ('City', models.CharField(max_length=30, verbose_name='Ville')),
                ('Company', models.CharField(max_length=30, verbose_name='Compagnie')),
                ('Country', models.CharField(max_length=30, verbose_name='Pays')),
                ('Description', models.CharField(max_length=150, verbose_name='Description')),
                ('DisplayName', models.CharField(max_length=30, verbose_name="Nom d'affichage")),
                ('EmailAddress', models.CharField(max_length=350, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Utilisateur AD',
                'verbose_name_plural': 'Utilisateurs AD',
            },
        ),
    ]
