# Generated by Django 2.0.5 on 2018-05-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanager',
            name='newuser',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
