# Generated by Django 2.0.5 on 2018-05-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0004_auto_20180528_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name="Nom de l'article")),
                ('description', models.CharField(max_length=200, verbose_name="Description de l'article")),
                ('type', models.CharField(max_length=100, verbose_name="Type d'article")),
                ('service', models.CharField(max_length=50, verbose_name='Service')),
                ('piece', models.CharField(max_length=50, verbose_name='Pièce')),
                ('derniere_commande', models.DateField(verbose_name='Dernière commande')),
                ('fournisseur', models.CharField(max_length=50, verbose_name='Fournisseur')),
                ('date_expiration_garantie', models.DateField(verbose_name='Fin de la garantie')),
                ('condition', models.CharField(max_length=50, verbose_name="Condition de l'article")),
                ('quantité', models.IntegerField(verbose_name='Quantité')),
                ('prix_achat', models.FloatField(verbose_name="Prix d'achat")),
                ('prix_reel', models.FloatField(verbose_name='Prix réel')),
            ],
        ),
    ]
