# Generated by Django 2.0.5 on 2018-05-29 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_inventaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250, verbose_name='Note')),
                ('date', models.DateTimeField(verbose_name='Date et heure')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='prix_reel',
        ),
        migrations.RemoveField(
            model_name='inventaire',
            name='quantité',
        ),
        migrations.AddField(
            model_name='inventaire',
            name='prix',
            field=models.FloatField(default=0, verbose_name='Prix par item'),
        ),
        migrations.AddField(
            model_name='inventaire',
            name='quantite',
            field=models.IntegerField(default=1, verbose_name='Quantité'),
        ),
    ]
