# Generated by Django 2.0.5 on 2018-05-29 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180529_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 3, 20, 30, 337841), verbose_name='Date et heure'),
        ),
    ]
