# Generated by Django 2.0.5 on 2018-05-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180529_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date et heure'),
        ),
    ]
