# Generated by Django 2.0.5 on 2018-05-29 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180529_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 7, 26, 20, 729059, tzinfo=utc), verbose_name='Date et heure'),
        ),
    ]
