# Generated by Django 2.0.5 on 2018-05-29 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180529_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 3, 29, 17, 283118), verbose_name='Date et heure'),
        ),
    ]
