# Generated by Django 2.0.5 on 2018-05-29 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180529_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 14, 38, 35, 586822), verbose_name='Date et heure'),
        ),
    ]
