# Generated by Django 2.0.5 on 2018-05-29 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180529_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 18, 7, 58, 998610), verbose_name='Date et heure'),
        ),
    ]
