# Generated by Django 2.0.5 on 2018-05-30 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180529_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 10, 55, 6, 659988), verbose_name='Date et heure'),
        ),
    ]
