# Generated by Django 2.0.5 on 2018-05-30 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180530_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 30, 10, 56, 1, 997033), verbose_name='Date et heure'),
        ),
    ]
